disabled_rules: # rule identifiers to exclude from running
  - file_length
  - operator_whitespace
  - todo
opt_in_rules: # some rules are only opt-in
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - control_statement
  - empty_count
  - explicit_init
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - no_grouping_extension
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - private_unit_test
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  #  - sorted_first_last  # rule is not found in 2017-11-10 build of SwiftLint
  #  - sorted_imports     # docs incorrect: placing comment between two imports does not reset the ordering calculation
  #  - trailing_closure   # rule does not ignore functional methods, which SHOULD use () to enable chaining
  - vertical_parameter_alignment_on_call
included: # paths to include during linting. `--path` is ignored if present.
  - Sources
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Vendor
  - bin

reporter: "emoji" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

# rule configuration
identifier_name:
  excluded: 
    - cmd
    - id
    - url
    - vc
line_length: 
  warning: 132
type_name:
  max_length:
    warning: 60
vertical_whitespace: 
  max_empty_lines: 2
